### PR TITLE
Implement linking of IP Adresses to newly created device.

### PR DESCRIPTION
**Pull request by ByteOtter**
# What does this PR change?

Currently we can only create devices without the IP address fields being set.

This PR aims to fix that. For this, after device creation, we need to create an Interface for the device, create an IP address object and then PATCH the device with the ID of its primary IP address linked to one of its devices.

As references serve these threads:

https://github.com/netbox-community/netbox/discussions/8746

https://github.com/netbox-community/netbox/discussions/8837

Tick the applicable box:
- [x] Add new feature
- [ ] Security changes
- [ ] Tests
- [x] Documentation changed
<br/>

- [ ] General Maintenance

## Links

Fixes: #69 

- [x] DONE

## Documentation

- No documentation needed
<br/>

- [x] DONE

### CODE REVIEW

**Comment by ByteOtter** [comment]
Currently we do not get a valid JSON response body when the creation is successful. We need to investigate if this issue is on our end or on theirs.
A possible workaround could look like this:

1. Create interface only checking for valid errors and ignoring JSON parsing errors.
2. Get list of all Interfaces from NetBox
3. Search list for the interface we just created. Best guess would be the MAC-Address?

Problems with this workaround:
- Will not work for prototype hardware without a valid MAC-Address
- MAC-Address and name fields are not necessarily unique or even present as they are optional

**Comment by ByteOtter** [comment]
After further investigation, it definitely looks like this is a problem on NetBox's end.
Looking at the fields `link_peers_type` and `connected_endpoints` in the `Interface` struct, we can see that the schema requires them to be a `String` and a `Vec`. Which gets translated correctly in `thanix_client`.
However, the application returns both of these values as `null`, which does not correspond with the schema.

This leads to several conclusions:
1. This could a problem that can re-occur in more fields than the ones we encountered here.
2. A temporary workaround is required to allow `v0.1.0` to be working with NetBox `v3.6.x` as per the decision made in #74.
3. An automated integration test suite is required to catch these errors correctly.

Backend bug hunting must also be conducted as we cannot be sure this problem is fixed with NetBox `v4.x`.
I had opened an issue with NetBox about a possible bug on this end (https://github.com/netbox-community/netbox/issues/16301) they asserted that this is not an issue with them. We need to collect further information before we can proceed to report a bug again.

**Review by marv7000 — APPROVED** [review]
LGTM

**Review by SchoolGuy — APPROVED** [review]
LGTM. The fine details can be fixed later. :)

**Pull request merged**
